# by www.bejson.com 
kind: Service
apiVersion: v1
metadata: 
  name: admin-api-svc
  namespace: default
  labels:
    run: nginx
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: web
    port: 80
    targetPort: 80
  selector: 
    name: admin-api
